[theme]
primaryColor = "#0284c7"
backgroundColor = "#080c14"
secondaryBackgroundColor = "#0f172a"
textColor = "#f1f5f9"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
